### ISSUE TITLE
Currently missing BitInt Literal support

### ISSUE THREAD

**Issue by JakeChampion** [NerdLang/nerd#102]
It looks like NectarJS is currently missing [BigInt Literal](https://tc39.es/ecma262/#prod-BigIntLiteralSuffix) support.

Steps to reproduce the issue:
1 - Install latest nectarjs
2 - Run these two commands
```
❯ echo "0n" > big-int.js
❯ nectar big-int.js
```
3 - Should see this error message from previous command
```
[*] Generating source file
[error] Parsing error: Identifier directly after number line 1 column 2 in file big-int.js
```

**Comment by adrien-thierry** [comment]
Hi @JakeChampion , thank you

**Comment by JakeChampion** [comment]
I see this has been labelled es5. I figure I should mention that BigInt was added in es2020, which is the 11th edition and not in es5.

Not sure if that changes anything but just in case you thought it was an es5 feature 👍

**Comment by adrien-thierry** [comment]
Yes thx my bad, i was too fast
